server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/consumidor
    username: root
    password: root
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
              
spring.flyway.baseline-on-migrate: true
