server:
  port: 8083
spring:
     datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://sve-dllo.ceiba.com.co/expone
      username: svedllo
      password: $v3Dll019**

              
spring.flyway.baseline-on-migrate: true